use serde_json::{json, Value};
use std::path::Path;

const MARKER: &str = "HUMHUM_OPENCLAW_HOOK";
const ENTRY_NAME: &str = "humhum-openclaw";

const HOOK_MANIFEST: &str = r#"---
name: humhum-openclaw
description: "Forward local OpenClaw lifecycle events to HUMHUM"
metadata:
  { "openclaw": { "events": ["command", "message", "session"] } }
---

<!-- HUMHUM_OPENCLAW_HOOK -->

# HUMHUM OpenClaw Hook

Generated by HUMHUM. Reinstall from HUMHUM settings to refresh it.
"#;

const HANDLER_SOURCE: &str = r#"// HUMHUM_OPENCLAW_HOOK
// Generated local-only observer. Reinstall from HUMHUM settings to refresh it.

import { readFile } from "node:fs/promises";
import { homedir } from "node:os";
import { join } from "node:path";

type UnknownRecord = Record<string, any>;

let deliveryQueue: Promise<void> = Promise.resolve();

function stableString(value: unknown): string | undefined {
  if (typeof value === "string") {
    const trimmed = value.trim();
    return trimmed || undefined;
  }
  if (typeof value === "number") return String(value);
  return undefined;
}

function firstString(...values: unknown[]): string | undefined {
  for (const value of values) {
    const normalized = stableString(value);
    if (normalized) return normalized;
  }
  return undefined;
}

function summarize(value: unknown): string | undefined {
  if (typeof value === "string") return stableString(value);
  if (Array.isArray(value)) {
    const parts = value.map(summarize).filter(Boolean);
    return parts.length ? parts.join("\n") : undefined;
  }
  if (value && typeof value === "object") {
    const record = value as UnknownRecord;
    return firstString(
      summarize(record.text),
      summarize(record.body),
      summarize(record.message),
      summarize(record.content),
    );
  }
  return undefined;
}

function eventName(event: UnknownRecord): string | undefined {
  const key = `${event?.type ?? ""}:${event?.action ?? ""}`;
  switch (key) {
    case "command:new":
    case "command:reset":
      return "SessionStart";
    case "command:stop":
      return "SessionEnd";
    case "message:received":
      return "UserPromptSubmit";
    case "message:sent":
      return "Stop";
    case "session:compact:before":
      return "PreCompact";
    case "session:compact:after":
    case "session:patch":
      return "Notification";
    default:
      return undefined;
  }
}

function buildPayload(event: UnknownRecord): UnknownRecord | undefined {
  const context = event?.context && typeof event.context === "object" ? event.context : {};
  const entry = context.sessionEntry && typeof context.sessionEntry === "object"
    ? context.sessionEntry
    : {};
  const patch = context.patch && typeof context.patch === "object" ? context.patch : {};
  const rawSessionId = firstString(
    entry.id,
    entry.sessionID,
    entry.sessionId,
    patch.sessionID,
    patch.sessionId,
    event.sessionKey,
    event.sessionID,
    event.sessionId,
    context.sessionKey,
    context.sessionID,
    context.sessionId,
  );
  const hookEventName = eventName(event);
  if (!rawSessionId || !hookEventName) return undefined;
  const sessionId = rawSessionId.startsWith("openclaw-")
    ? rawSessionId
    : `openclaw-${rawSessionId}`;
  const message = summarize(context.content)
    ?? summarize(context.bodyForAgent)
    ?? summarize(context.message)
    ?? summarize(context.patch);
  const cwd = firstString(
    context.workspaceDir,
    context.workspace?.dir,
    context.directory,
    entry.workspaceDir,
    entry.directory,
    context.cfg?.workspace?.dir,
  );
  return {
    hook_event_name: hookEventName,
    session_id: sessionId,
    client_type: "openclaw",
    thread_source: "openclaw-hooks",
    ...(cwd ? { cwd } : {}),
    ...(message ? { message } : {}),
    ...(hookEventName === "UserPromptSubmit" && message ? { prompt: message } : {}),
    ...(hookEventName === "Stop" && message ? { last_assistant_message: message } : {}),
    source_event: `${event?.type ?? "unknown"}:${event?.action ?? "unknown"}`,
  };
}

async function deliver(payload: UnknownRecord): Promise<void> {
  try {
    const humhumDir = join(process.env.HOME || homedir(), ".humhum");
    const [configText, tokenText] = await Promise.all([
      readFile(join(humhumDir, "config.json"), "utf8"),
      readFile(join(humhumDir, "local-api-token"), "utf8"),
    ]);
    const port = Number(JSON.parse(configText)?.hook_port ?? 31275);
    const token = tokenText.trim();
    if (!Number.isInteger(port) || port < 1 || port > 65535 || !token) return;
    await fetch(`http://127.0.0.1:${port}/event`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "X-HumHum-Token": token,
      },
      body: JSON.stringify(payload),
      signal: AbortSignal.timeout(1000),
    });
  } catch {
    // OpenClaw must continue when HUMHUM is unavailable.
  }
}

const handler = async (event: UnknownRecord): Promise<void> => {
  const payload = buildPayload(event);
  if (!payload) return;
  deliveryQueue = deliveryQueue.then(() => deliver(payload), () => deliver(payload));
};

export { buildPayload };
export default handler;
"#;

pub fn install_at(hook_dir: &Path, config_path: &Path) -> Result<(), String> {
    let mut config = read_config(config_path)?;
    set_activation(&mut config, true)?;
    std::fs::create_dir_all(hook_dir)
        .map_err(|error| format!("Could not create OpenClaw hook directory: {error}"))?;
    write_atomic(&hook_dir.join("HOOK.md"), HOOK_MANIFEST)?;
    write_atomic(&hook_dir.join("handler.ts"), HANDLER_SOURCE)?;
    write_json_atomic(config_path, &config)
}

pub fn uninstall_at(hook_dir: &Path, config_path: &Path) -> Result<(), String> {
    let managed = [hook_dir.join("HOOK.md"), hook_dir.join("handler.ts")];
    for path in &managed {
        if path.exists() {
            let source = std::fs::read_to_string(path)
                .map_err(|error| format!("Could not inspect OpenClaw hook: {error}"))?;
            if !source.contains(MARKER) {
                return Err("Refusing to remove an unmanaged OpenClaw hook".into());
            }
        }
    }
    let mut config = read_config(config_path)?;
    set_activation(&mut config, false)?;
    write_json_atomic(config_path, &config)?;
    for path in managed {
        if path.exists() {
            std::fs::remove_file(path)
                .map_err(|error| format!("Could not remove OpenClaw hook file: {error}"))?;
        }
    }
    if hook_dir.exists()
        && std::fs::read_dir(hook_dir)
            .map_err(|error| format!("Could not inspect OpenClaw hook directory: {error}"))?
            .next()
            .is_none()
    {
        std::fs::remove_dir(hook_dir)
            .map_err(|error| format!("Could not remove OpenClaw hook directory: {error}"))?;
    }
    Ok(())
}

pub fn is_installed_at(hook_dir: &Path, config_path: &Path) -> bool {
    let files_owned = [hook_dir.join("HOOK.md"), hook_dir.join("handler.ts")]
        .iter()
        .all(|path| std::fs::read_to_string(path).is_ok_and(|source| source.contains(MARKER)));
    files_owned
        && read_config(config_path).is_ok_and(|config| {
            config
                .pointer("/hooks/internal/entries/humhum-openclaw/enabled")
                .and_then(Value::as_bool)
                == Some(true)
        })
}

fn read_config(path: &Path) -> Result<Value, String> {
    if !path.exists() {
        return Ok(json!({}));
    }
    let source = std::fs::read_to_string(path)
        .map_err(|error| format!("Could not read OpenClaw config: {error}"))?;
    let config: Value = serde_json::from_str(&source)
        .map_err(|error| format!("Could not parse OpenClaw config: {error}"))?;
    if !config.is_object() {
        return Err("OpenClaw config root must be an object".into());
    }
    Ok(config)
}

fn set_activation(config: &mut Value, enabled: bool) -> Result<(), String> {
    let root = config
        .as_object_mut()
        .ok_or_else(|| "OpenClaw config root must be an object".to_string())?;
    let hooks = object_entry(root, "hooks")?;
    let internal = object_entry(hooks, "internal")?;
    let entries = object_entry(internal, "entries")?;
    if enabled {
        let entry = entries
            .entry(ENTRY_NAME)
            .or_insert_with(|| json!({}))
            .as_object_mut()
            .ok_or_else(|| "OpenClaw HUMHUM hook entry must be an object".to_string())?;
        entry.insert("enabled".into(), Value::Bool(true));
    } else {
        entries.remove(ENTRY_NAME);
        if entries.is_empty() {
            internal.remove("entries");
        }
        if internal.is_empty() {
            hooks.remove("internal");
        }
        if hooks.is_empty() {
            root.remove("hooks");
        }
    }
    Ok(())
}

fn object_entry<'a>(
    parent: &'a mut serde_json::Map<String, Value>,
    key: &str,
) -> Result<&'a mut serde_json::Map<String, Value>, String> {
    parent
        .entry(key)
        .or_insert_with(|| json!({}))
        .as_object_mut()
        .ok_or_else(|| format!("OpenClaw config field {key} must be an object"))
}

fn write_json_atomic(path: &Path, value: &Value) -> Result<(), String> {
    let source = serde_json::to_string_pretty(value)
        .map_err(|error| format!("Could not serialize OpenClaw config: {error}"))?;
    write_atomic(path, &format!("{source}\n"))
}

fn write_atomic(path: &Path, content: &str) -> Result<(), String> {
    let parent = path
        .parent()
        .ok_or_else(|| "Invalid OpenClaw managed path".to_string())?;
    std::fs::create_dir_all(parent)
        .map_err(|error| format!("Could not create OpenClaw directory: {error}"))?;
    let name = path
        .file_name()
        .and_then(|name| name.to_str())
        .ok_or_else(|| "Invalid OpenClaw managed file name".to_string())?;
    let temporary = path.with_file_name(format!(".{name}.{}.tmp", uuid::Uuid::new_v4()));
    std::fs::write(&temporary, content)
        .map_err(|error| format!("Could not write OpenClaw managed file: {error}"))?;
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let mode = std::fs::metadata(path)
            .map(|metadata| metadata.permissions().mode() & 0o777)
            .unwrap_or(0o600);
        std::fs::set_permissions(&temporary, std::fs::Permissions::from_mode(mode))
            .map_err(|error| format!("Could not protect OpenClaw managed file: {error}"))?;
    }
    std::fs::rename(&temporary, path)
        .map_err(|error| format!("Could not install OpenClaw managed file: {error}"))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn install_activates_owned_hook_without_replacing_other_config() {
        let temp = tempfile::tempdir().unwrap();
        let hook_dir = temp.path().join("hooks/humhum-openclaw");
        let config_path = temp.path().join("openclaw.json");
        std::fs::write(
            &config_path,
            r#"{"private":"keep","hooks":{"internal":{"enabled":true,"entries":{"other":{"enabled":false}}}}}"#,
        )
        .unwrap();

        install_at(&hook_dir, &config_path).unwrap();

        let manifest = std::fs::read_to_string(hook_dir.join("HOOK.md")).unwrap();
        let handler = std::fs::read_to_string(hook_dir.join("handler.ts")).unwrap();
        assert!(manifest.contains("HUMHUM_OPENCLAW_HOOK"));
        assert!(handler.contains("HUMHUM_OPENCLAW_HOOK"));
        assert!(manifest.contains(r#"["command", "message", "session"]"#));
        for event in [
            "SessionStart",
            "SessionEnd",
            "UserPromptSubmit",
            "Stop",
            "PreCompact",
            "Notification",
        ] {
            assert!(handler.contains(event), "handler missing {event}");
        }
        let config: serde_json::Value =
            serde_json::from_str(&std::fs::read_to_string(&config_path).unwrap()).unwrap();
        assert_eq!(config["private"], "keep");
        assert_eq!(
            config["hooks"]["internal"]["entries"]["other"]["enabled"],
            false
        );
        assert_eq!(
            config["hooks"]["internal"]["entries"]["humhum-openclaw"]["enabled"],
            true
        );
        assert!(is_installed_at(&hook_dir, &config_path));

        std::fs::remove_file(hook_dir.join("handler.ts")).unwrap();
        assert!(!is_installed_at(&hook_dir, &config_path));
        install_at(&hook_dir, &config_path).unwrap();
        uninstall_at(&hook_dir, &config_path).unwrap();

        let config: serde_json::Value =
            serde_json::from_str(&std::fs::read_to_string(&config_path).unwrap()).unwrap();
        assert_eq!(config["private"], "keep");
        assert!(config["hooks"]["internal"]["entries"]
            .get("humhum-openclaw")
            .is_none());
        assert_eq!(
            config["hooks"]["internal"]["entries"]["other"]["enabled"],
            false
        );
        assert!(!hook_dir.exists());
    }

    #[test]
    fn uninstall_refuses_an_unmanaged_hook_before_changing_config() {
        let temp = tempfile::tempdir().unwrap();
        let hook_dir = temp.path().join("humhum-openclaw");
        let config_path = temp.path().join("openclaw.json");
        std::fs::create_dir_all(&hook_dir).unwrap();
        std::fs::write(hook_dir.join("HOOK.md"), "# Personal hook\n").unwrap();
        std::fs::write(hook_dir.join("handler.ts"), "export default () => {};\n").unwrap();
        let original = r#"{"hooks":{"internal":{"entries":{"humhum-openclaw":{"enabled":true}}}}}"#;
        std::fs::write(&config_path, original).unwrap();

        let error = uninstall_at(&hook_dir, &config_path).unwrap_err();

        assert!(error.contains("unmanaged OpenClaw hook"));
        assert_eq!(std::fs::read_to_string(config_path).unwrap(), original);
        assert!(hook_dir.join("HOOK.md").exists());
        assert!(hook_dir.join("handler.ts").exists());
    }

    #[test]
    fn uninstall_restores_config_when_humhum_created_the_hook_parents() {
        let temp = tempfile::tempdir().unwrap();
        let hook_dir = temp.path().join("hooks/humhum-openclaw");
        let config_path = temp.path().join("openclaw.json");
        let original: Value = json!({ "private": "keep" });
        std::fs::write(
            &config_path,
            serde_json::to_string_pretty(&original).unwrap(),
        )
        .unwrap();

        install_at(&hook_dir, &config_path).unwrap();
        uninstall_at(&hook_dir, &config_path).unwrap();

        let restored: Value =
            serde_json::from_str(&std::fs::read_to_string(config_path).unwrap()).unwrap();
        assert_eq!(restored, original);
    }

    #[test]
    fn generated_handler_delivers_ordered_authenticated_events() {
        let temp = tempfile::tempdir().unwrap();
        let hook_dir = temp.path().join("hooks/humhum-openclaw");
        let openclaw_config = temp.path().join("openclaw.json");
        install_at(&hook_dir, &openclaw_config).unwrap();
        let handler_url = format!("file://{}", hook_dir.join("handler.ts").display());
        let runner = temp.path().join("smoke.mjs");
        let script = format!(
            r#"
import http from "node:http";
import {{ mkdir, writeFile }} from "node:fs/promises";
import {{ join }} from "node:path";
import handler from {handler_url:?};

const events = [];
const headers = [];
const server = http.createServer((request, response) => {{
  const chunks = [];
  request.on("data", (chunk) => chunks.push(chunk));
  request.on("end", () => {{
    events.push(JSON.parse(Buffer.concat(chunks).toString("utf8")));
    headers.push(request.headers["x-humhum-token"]);
    response.writeHead(204);
    response.end();
  }});
}});
await new Promise((resolve) => server.listen(0, "127.0.0.1", resolve));
const humhum = join(process.env.HOME, ".humhum");
await mkdir(humhum, {{ recursive: true }});
await writeFile(join(humhum, "config.json"), JSON.stringify({{ hook_port: server.address().port }}));
await writeFile(join(humhum, "local-api-token"), "openclaw-smoke-token\n");

const context = {{ workspaceDir: "/tmp/openclaw-workspace", content: "hello" }};
const returns = [];
returns.push(await handler({{ type: "message", action: "received", context }}));
returns.push(await handler({{ type: "command", action: "new", sessionKey: "session-1", context }}));
returns.push(await handler({{ type: "message", action: "received", sessionKey: "session-1", context }}));
returns.push(await handler({{ type: "session", action: "compact:before", sessionKey: "session-1", context }}));
returns.push(await handler({{ type: "session", action: "compact:after", sessionKey: "session-1", context }}));
returns.push(await handler({{ type: "session", action: "patch", sessionKey: "session-1", context }}));
returns.push(await handler({{ type: "message", action: "sent", sessionKey: "session-1", context }}));
returns.push(await handler({{ type: "command", action: "stop", sessionKey: "session-1", context }}));

const deadline = Date.now() + 5000;
while (events.length < 7 && Date.now() < deadline) {{
  await new Promise((resolve) => setTimeout(resolve, 20));
}}
await new Promise((resolve) => server.close(resolve));
console.log(JSON.stringify({{ events, headers, returns }}));
"#
        );
        std::fs::write(&runner, script).unwrap();

        let output = std::process::Command::new("node")
            .arg("--experimental-strip-types")
            .arg(&runner)
            .env("HOME", temp.path())
            .output()
            .unwrap();
        assert!(
            output.status.success(),
            "{}",
            String::from_utf8_lossy(&output.stderr)
        );
        let result: Value = serde_json::from_slice(&output.stdout).unwrap();
        let events = result["events"].as_array().unwrap();
        let names: Vec<&str> = events
            .iter()
            .map(|event| event["hook_event_name"].as_str().unwrap())
            .collect();
        assert_eq!(
            names,
            [
                "SessionStart",
                "UserPromptSubmit",
                "PreCompact",
                "Notification",
                "Notification",
                "Stop",
                "SessionEnd",
            ]
        );
        assert!(events.iter().all(|event| {
            event["client_type"] == "openclaw"
                && event["session_id"] == "openclaw-session-1"
                && event["thread_source"] == "openclaw-hooks"
                && event["cwd"] == "/tmp/openclaw-workspace"
        }));
        assert!(result["headers"]
            .as_array()
            .unwrap()
            .iter()
            .all(|header| header == "openclaw-smoke-token"));
        assert_eq!(result["returns"].as_array().unwrap().len(), 8);
        assert!(result["returns"]
            .as_array()
            .unwrap()
            .iter()
            .all(Value::is_null));
    }

    #[test]
    #[ignore = "writes to an explicitly supplied OpenClaw home"]
    fn installs_into_an_explicit_openclaw_home() {
        let home = std::env::var_os("HUMHUM_OPENCLAW_LIVE_HOME")
            .expect("HUMHUM_OPENCLAW_LIVE_HOME is required");
        let home = std::path::PathBuf::from(home);

        install_at(
            &home.join("hooks/humhum-openclaw"),
            &home.join("openclaw.json"),
        )
        .unwrap();

        assert!(is_installed_at(
            &home.join("hooks/humhum-openclaw"),
            &home.join("openclaw.json"),
        ));
    }
}
